### ISSUE TITLE
Github actions `pkgdown` workflow fails to build file `NEWS.md`

### ISSUE THREAD

**Issue by dpc10ster** [dpc10ster/RJafroc#74]
The build fails *only* if the file `NEWS.md` is present in the project root. 

As a temporary fix I have moved it to directory `inst` and renamed it to `my_NEWS.md` (if the renamed file is in the project root then I get the same failure as with the original file name).

Of course this means that the `Changelog` feature is no longer present in the project website.

**Comment by pwep** [comment]
Looking at the action's log, there is a warning being generated when reading the news file (usually `NEWS.md`). I can replicate the error locally by calling `pkgdown::build_news()`. A total of 14 warnings are generated. I have pinned it down to the line below.
https://github.com/dpc10ster/RJafroc/blob/7e82dedd02a53c7af74154fa16709d74ea08081c/inst/my_NEWS.md?plain=1#L76 
The `?` followed by some characters, wrapped in the inline code ticks, seems to generate the warnings.
Replace the `?` with a `*` and the warnings no longer occur. The `*` would be the correct character to use to match the intent of the sentence.
The warnings feel like they have been introduced by a markdown parser we depend on, so outside of our control.

**Comment by dpc10ster** [comment]
Thank you! That fixed it. Dev

**Comment by dpc10ster** [comment]
The error message was 
```
In if (has_name(index, topic)) { ... :
  the condition has length > 1 and only the first element will be used
```
repeated 14 times. 

How did you got to line 76 as the cause for these warnings?

**Comment by pwep** [comment]
As you identified, the action failure was caused by the `NEWS.md` file. After looking at the action log, I made a simple `NEWS.md` file and started adding news sections until I got the warnings, and eventually was able to isolate the line. The `?` and `.` characters were a likely cause of the warnings. The inline code block is not being executed, just rendered in HTML in the code style, and these were only warnings, not full errors. Duplicate line 76 and you get 28 warnings.
Thank goodness `pkgdown::build_news()` was available, as it allowed me to focus on building just the news file rather than the whole package.
