### ISSUE TITLE
Running Significance testing on LROC type data

### ISSUE THREAD

**Issue by MPEngbersen** [dpc10ster/RJafroc#91]
Hi, I'm having trouble with the significance testing function of my LROC data. 
Using the latest GitHub version of the RJafroc package (v2.1.3) with R version 4.2.2.

I keep seeing the following errors with our own data but also with the data provided with the package:

> library(RJafroc)
> packageVersion("RJafroc")
[1] ‘2.1.3’
> d <- DfFroc2Lroc(dataset04)
> p <- PlotEmpiricalOperatingCharacteristics(d, trts = list(1,2), rdrs = list( c(1,2), c(1,2)), opChType = "LROC")
> p$Plot
> St(d, FOM = 'ALROC', FPFValue = 0.2, method = 'OR')
Error in AddTruthTableStr(dataset, dataset$descriptions$type, dataset$lesions$perCase) : 
  data type must be ROC or FROC`

A different error message with the CRAN version (2.1.2) mentioned:
`Error in t[i, j, , 1] : incorrect number of dimensions`

Am I missing something? 
Any help would be greatly appreciated.

**Comment by pwep** [comment]
Thanks for raising this issue.
This appears to be due to a missing `truthTableStr` for the dataset.

- the `DfFroc2Lroc` function appears not to pass or recalculate a new truth table during the conversion
- the `AddTruthTableStr` function does not support an `LROC` type

These appear to have been relatively recent changes to the codebase, based on the comments @dpc10ster has added.

I will step through earlier versions of the package to try and catch where any breaking changes might have been made. I will add further updates to this issue as I progress.
